name: Update Auction Data

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'fetch_uppbod.py'

jobs:
  fetch-uppbod:
    if: github.event_name != 'push' || github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Ensure credentials are available
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Run fetch_uppbod.py
      run: python fetch_uppbod.py

    - name: Configure git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"

    - name: Commit changes
      run: |
        git add auction_data.csv
        git commit -m "Update auction data [skip ci]" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin HEAD:${{ github.ref }}
